
services:
  todo-app:
    image: todo:latest
    build: .
    container_name: todo-container
    ports:
      - "8000:3000"
    volumes:
      - ./sqlite.db:/app/sqlite.db
      - ./logs:/app/logs
    environment:
      - NODE_ENV=production
      - ACCESS_SECRET="KFC-CRAZY-THURSDAY-VME50"
      - REFRESH_SECRET="KFC-CRAZY-THURSDAY-VME50"
      # 建议通过环境变量传递 Redis 地址
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    restart: always

  # --- 新增 Redis 服务 ---
  redis:
    image: redis:alpine
    container_name: redis-server
    restart: always

